name: Update artifact
on: workflow_dispatch
jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Update artifact
        run: |
          dest=$PWD
          git clone https://github.com/tuanchauict/MonoSketch.git --branch=release/alpha/1.1.0 --single-branch ../src
          cd ../src
          ./gradlew assemble
          src=$PWD
          hash=$(git rev-parse HEAD)
          cd $dest
          sh tools/release.sh $src/build/distributions $hash
